-- Users table seeds here (Example)
INSERT INTO users (name, email, password, phone) VALUES ('Alice', 'alice@alice.com', 'password', '1234567890');
INSERT INTO users (name, email, password, phone) VALUES ('Kira', 'kira@kira.com', 'password', '1234567890');
INSERT INTO users (name, email, password, phone) VALUES ('johnny', 'johnny@johnny.com', 'passwprd', '1234567890');
insert into users (name, email, password, phone) values ('Bertine Vowell', 'bvowell0@artisteer.com', 'Violet', '328-489-7486');
insert into users (name, email, password, phone) values ('Niels Lonnon', 'nlonnon1@wordpress.com', 'Maroon', '412-559-5449');
insert into users (name, email, password, phone) values ('Colver Sellick', 'csellick2@fastcompany.com', 'Mauv', '583-877-8890');
insert into users (name, email, password, phone) values ('Margarette O''Regan', 'moregan3@ehow.com', 'Goldenrod', '839-259-8674');
insert into users (name, email, password, phone) values ('Raynard Whysall', 'rwhysall4@elpais.com', 'Mauv', '703-872-8311');
insert into users (name, email, password, phone) values ('Tobie Wickett', 'twickett5@sphinn.com', 'Purple', '577-810-2004');
insert into users (name, email, password, phone) values ('Caralie Poltun', 'cpoltun6@wsj.com', 'Red', '800-120-8014');
insert into users (name, email, password, phone) values ('Victoria Matityahu', 'vmatityahu7@rediff.com', 'Red', '871-584-1844');
insert into users (name, email, password, phone) values ('Bree Waitland', 'bwaitland8@hhs.gov', 'Green', '364-946-0899');
insert into users (name, email, password, phone) values ('Imelda Ohms', 'iohms9@un.org', 'Pink', '221-930-3807');
insert into users (name, email, password, phone) values ('Becki Mangon', 'bmangona@hao123.com', 'Khaki', '145-537-5428');
insert into users (name, email, password, phone) values ('Gav Twigg', 'gtwiggb@amazon.de', 'Puce', '478-585-4939');
insert into users (name, email, password, phone) values ('Claus Ahrens', 'cahrensc@instagram.com', 'Red', '410-124-5538');
insert into users (name, email, password, phone) values ('Addy Oakwell', 'aoakwelld@latimes.com', 'Teal', '811-497-2846');
insert into users (name, email, password, phone) values ('Griz Cahill', 'gcahille@msu.edu', 'Blue', '911-531-8116');
insert into users (name, email, password, phone) values ('Alyosha Witherup', 'awitherupf@mediafire.com', 'Goldenrod', '959-701-9515');
insert into users (name, email, password, phone) values ('Fancy Coveney', 'fcoveneyg@github.io', 'Green', '704-528-8437');
insert into users (name, email, password, phone) values ('Wynn McKirdy', 'wmckirdyh@bizjournals.com', 'Fuscia', '546-896-8865');
insert into users (name, email, password, phone) values ('Jackelyn Ellis', 'jellisi@bandcamp.com', 'Teal', '236-164-8510');
insert into users (name, email, password, phone) values ('Aubrie Featonby', 'afeatonbyj@umich.edu', 'Goldenrod', '855-764-2066');
